# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Matcompart
tagline:          'Technology and math'
description:      'not defined yet'
url:              http://Matcompart.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
github:
  repo:           
